//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-M3K4EN6H\\SQLEXPRESS;Initial Catalog=QL_DCAN2;Integrated Securi" +
            "ty=True")]
        public string QL_DCAN2ConnectionString {
            get {
                return ((string)(this["QL_DCAN2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-M3K4EN6H\\SQLEXPRESS;Initial Catalog=QL_DCAN1;Integrated Securi" +
            "ty=True")]
        public string QL_DCAN1ConnectionString {
            get {
                return ((string)(this["QL_DCAN1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-TQQS6PK;Initial Catalog=QL_DCAN;Persist Security Info=True;Us" +
            "er ID=sa;Password=123;Encrypt=True;TrustServerCertificate=True")]
        public string QL_DCANConnectionString {
            get {
                return ((string)(this["QL_DCANConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-TQQS6PK;Initial Catalog=QL_DCAN;User ID=sa;Password=123;Trust" +
            "ServerCertificate=True")]
        public string QL_DCANConnectionString1 {
            get {
                return ((string)(this["QL_DCANConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-M3K4EN6H\\SQLEXPRESS;Initial Catalog=QL_DCAN1;User ID=vy;Passwo" +
            "rd=123")]
        public string QL_DCAN1ConnectionString1 {
            get {
                return ((string)(this["QL_DCAN1ConnectionString1"]));
            }
        }
    }
}
